import { projectBySlug } from "@/content/projects";

/**
 * The three most recent posts from the blog, read at build time.
 *
 * The hub linked the blog once, from a footer list, under a project name that
 * says nothing about what is written there. This puts the actual titles and
 * descriptions on the hub as indexable text, with internal links carrying
 * those titles as anchor text — which is the half of hub-and-spoke the
 * arrangement was missing.
 *
 * The feed URL is derived from the portfolio entry rather than written here,
 * the same way the header and footer links are.
 */

export interface Post {
  title: string;
  url: string;
  summary: string;
  /** ISO 8601, straight from the feed. */
  published: string;
}

const BLOG = projectBySlug("tech-perspectives")?.links.live;

/** How many appear on the home page. */
const LIMIT = 3;

const ENTITIES: Record<string, string> = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&#39;": "'",
  "&apos;": "'",
  "&nbsp;": " ",
};

/**
 * Feed text to plain text.
 *
 * Atom carries `type="html"`, so a title or summary may arrive wrapped in
 * CDATA, containing markup, and holding entities. All three have to come off
 * before the string is rendered as text.
 */
function plain(value: string): string {
  return value
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1")
    .replace(/<[^>]+>/g, "")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&[a-z]+;/gi, (entity) => ENTITIES[entity.toLowerCase()] ?? entity)
    .replace(/\s+/g, " ")
    .trim();
}

function firstMatch(source: string, pattern: RegExp): string | undefined {
  return pattern.exec(source)?.[1];
}

/**
 * Parsed with regular expressions rather than an XML library.
 *
 * This reads exactly one feed, generated by jekyll-feed from a repo in the
 * same hand, so the shape is known and stable — which is the only situation
 * where this is a reasonable trade against adding a parser dependency to a
 * site that otherwise has none. Every field is validated and an entry missing
 * a title or a link is dropped rather than rendered half-formed.
 */
function parseAtom(xml: string): Post[] {
  const posts: Post[] = [];

  for (const [, entry] of xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)) {
    const title = firstMatch(entry, /<title[^>]*>([\s\S]*?)<\/title>/);
    // `<link href=` rather than `href=`, so an anchor inside the post body
    // that jekyll-feed inlined into <content> cannot be mistaken for the
    // entry's own permalink.
    const url = firstMatch(entry, /<link[^>]*href="([^"]+)"/);
    const published = firstMatch(entry, /<published>([^<]+)<\/published>/);
    const summary = firstMatch(entry, /<summary[^>]*>([\s\S]*?)<\/summary>/);

    if (!title || !url) continue;

    posts.push({
      title: plain(title),
      url,
      summary: summary ? plain(summary) : "",
      published: published?.trim() ?? "",
    });
  }

  return posts;
}

/**
 * The revalidate window is what keeps the hub and the blog from drifting.
 *
 * Two things it is doing at once:
 *
 * `fetch` is uncached by default in this version of Next, and an uncached
 * fetch in a page opts that route out of static rendering. `next.revalidate`
 * opts back in — the build still reports `/` as Static, now with a one-hour
 * revalidate — so the home page does not quietly become dynamic, which is the
 * one thing this site says it never is.
 *
 * And it bounds staleness without coupling the two repositories. The obvious
 * alternative is a Vercel deploy hook called from the blog's workflow, which
 * is faster but depends on a secret staying valid and on that workflow
 * continuing to call it. When either quietly stops being true the hub goes
 * stale and nothing says so — which is the failure the coupling was meant to
 * prevent. A revalidate window cannot fail that way: it needs nothing from the
 * other repo, and it recovers on its own however a post came to be published.
 */
export async function recentPosts(limit = LIMIT): Promise<Post[]> {
  if (!BLOG) return [];

  try {
    const response = await fetch(`${BLOG}/feed.xml`, {
      next: { revalidate: 3600 },
      headers: { accept: "application/atom+xml, application/xml;q=0.9" },
    });

    if (!response.ok) {
      throw new Error(`feed responded ${response.status}`);
    }

    return parseAtom(await response.text()).slice(0, limit);
  } catch (error) {
    // A build that quietly drops the section and a blog with nothing new look
    // identical in the output, and only one of them is fine. Say so in the
    // build log rather than failing the build over a feed.
    console.warn(`[writing] could not read ${BLOG}/feed.xml —`, error);
    return [];
  }
}

/** The blog's own address, for the fallback and the "all posts" link. */
export const BLOG_URL = BLOG;
